### ISSUE TITLE
Missing test.csv file

### ISSUE THREAD

**Issue by jsomeara** [ProjectSidewalk/sidewalk-tagger-ai#1]
For the unvalidated dataset, the Crosswalk.zip file is missing test.csv. It only contains train.csv. Due to difficulties downloading, I have not been able to check the other zip files, but I would imagine they also have the same issue.

For the validated dataset, the test.csv file is there without any issues.

**Comment by jonfroehlich** [comment]
Can you be a bit more clear on why this was closed? Thanks!

**Comment by jonfroehlich** [comment]
Ahh, I see it from Slack:

> Unvalidated dataset doesn’t have it’s own test set. Both datasets use the same test set.
